# Generated by Django 5.2.8 on 2025-11-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0003_delete_contactinfo_delete_messagecontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='moyen',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='reference',
        ),
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money'), ('especes', 'Espèces')], default='carte', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='mode_livraison',
            field=models.CharField(choices=[('livraison', 'Livraison à domicile'), ('retrait', 'Retrait sur place')], default='livraison', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='boutique.order'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('termine', 'Terminé'), ('echoue', 'Échoué')], default='en_attente', max_length=20),
        ),
    ]
