# Generated by Django 5.2.8 on 2025-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_remove_order_adresse_remove_paiement_moyen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
